# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2cb6623c55b7422773efbb66896e8a8485bd02859007d446de6c500604aea9ba2636b63aa14caf07acbab76ab2f3a15d20430156eedb158569762c609c3a9d78

test:
  secret_key_base: 8768e4c7604286190ff7e5c7d0bd2eab70c26ac8d26f81c023dc5bdabf3d513541cbaddcd2226694ebeef4efdb406d9347886eae6381191d82bd9094dd51c02b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
